{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b991c6c5-e4a7-40c5-9466-9b518a30cd39",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "\n",
    "#Import libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.metrics import pairwise\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "#Load dataset\n",
    "df = pd.read_csv(\"mini_project.csv\")  # Make sure your CSV is ready\n",
    "\n",
    "#One-hot encode 'Type' column\n",
    "type_dummies = pd.get_dummies(df['Type'])\n",
    "df = pd.concat([df, type_dummies], axis=1)\n",
    "\n",
    "#Get user input from terminal\n",
    "user_type = input(\"Enter desired service type (Food/Shelter/Hospital): \").strip()\n",
    "user_max_distance = float(input(\"Enter maximum distance you can travel (km): \"))\n",
    "user_preferred_hours = float(input(\"Enter minimum working hours you prefer: \"))\n",
    "\n",
    "#Normalize numeric features for services\n",
    "df['Distance_norm'] = df['Distance_km'] / user_max_distance   # 0-1 scale\n",
    "df['Hours_norm'] = df['Working_Hours'] / 24                   # 0-1 scale\n",
    "\n",
    "#Create user vector (no importance weights)\n",
    "user_vector = np.array([\n",
    "    1 if user_type.lower() == 'food' else 0,\n",
    "    1 if user_type.lower() == 'shelter' else 0,\n",
    "    1 if user_type.lower() == 'hospital' else 0,\n",
    "    1,  # distance counted fully\n",
    "    1   # hours counted fully\n",
    "])\n",
    "\n",
    "#Create service vectors\n",
    "service_vectors = df[['Food','Shelter','Hospital','Distance_norm','Hours_norm']].values\n",
    "\n",
    "#Compute Euclidean distance using scikit-learn\n",
    "# Smaller distance = closer match\n",
    "distances = pairwise.euclidean_distances(service_vectors, user_vector.reshape(1,-1)).flatten()\n",
    "df['Distance_score'] = distances\n",
    "\n",
    "#Sort services by distance ascending (smaller = better)\n",
    "df_sorted = df.sort_values(by='Distance_score')\n",
    "top_services = df_sorted.head(5)\n",
    "\n",
    "#Display top 5 recommended services\n",
    "print(\"\\nTop 5 recommended services for you:\\n\")\n",
    "print(top_services[['Name','Type','Distance_km','Working_Hours','Distance_score']])\n",
    "\n",
    "#Visualization - Simulation\n",
    "x = df['Distance_norm']\n",
    "y = df['Hours_norm']\n",
    "\n",
    "plt.figure(figsize=(8,6))\n",
    "\n",
    "#Plot all services\n",
    "plt.scatter(x, y, c='lightblue', label='All Services', s=50)\n",
    "\n",
    "#Plot user as origin\n",
    "plt.scatter(0, 0, c='red', label='User', s=100)\n",
    "\n",
    "#Draw lines from user to all services\n",
    "for i in range(len(df)):\n",
    "    plt.plot([0, x[i]], [0, y[i]], c='gray', linewidth=0.5)\n",
    "\n",
    "#Highlight top 5 recommended services\n",
    "top_x = top_services['Distance_norm']\n",
    "top_y = top_services['Hours_norm']\n",
    "plt.scatter(top_x, top_y, c='green', label='Top Recommendations', s=80)\n",
    "\n",
    "plt.xlabel('Normalized Distance')\n",
    "plt.ylabel('Normalized Working Hours')\n",
    "plt.title('User vs Services Simulation (Euclidean Distance - scikit-learn)')\n",
    "plt.legend()\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
